export const STORAGE_CONSTANT={
    INTROSINGLESLIDER:'INTROSINGLESLIDER',
    INTROMULTISLIDER:'INTROMULTISLIDER'
}
export const EMAIl='siam@gmail.com';
export const HOME_TABS={
    INVITIES:'INVITIES',
    UPCOMING:'UPCOMING',
    COMPLETE:'COMPLETE'
    
}